
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 
* DO NOT EDIT.
*
* Copyright (C) 2010-2024 Xilinx, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT 

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xv_tpg.h"

/*
* The configuration table for devices
*/

XV_tpg_Config XV_tpg_ConfigTable[XPAR_XV_TPG_NUM_INSTANCES] =
{
	{
		XPAR_VIDEO_RX_V_TPG_0_DEVICE_ID,
		XPAR_VIDEO_RX_V_TPG_0_S_AXI_CTRL_BASEADDR,
		XPAR_VIDEO_RX_V_TPG_0_HAS_AXI4S_SLAVE,
		XPAR_VIDEO_RX_V_TPG_0_SAMPLES_PER_CLOCK,
		XPAR_VIDEO_RX_V_TPG_0_NUM_VIDEO_COMPONENTS,
		XPAR_VIDEO_RX_V_TPG_0_MAX_COLS,
		XPAR_VIDEO_RX_V_TPG_0_MAX_ROWS,
		XPAR_VIDEO_RX_V_TPG_0_MAX_DATA_WIDTH,
		XPAR_VIDEO_RX_V_TPG_0_SOLID_COLOR,
		XPAR_VIDEO_RX_V_TPG_0_RAMP,
		XPAR_VIDEO_RX_V_TPG_0_COLOR_BAR,
		XPAR_VIDEO_RX_V_TPG_0_DISPLAY_PORT,
		XPAR_VIDEO_RX_V_TPG_0_COLOR_SWEEP,
		XPAR_VIDEO_RX_V_TPG_0_ZONE_PLATE,
		XPAR_VIDEO_RX_V_TPG_0_FOREGROUND
	}
};


